In [1]:
print("Hello, Data Cleaning!")

Hello, Data Cleaning!

In [2]:
import pandas as pd
import numpy as np

In [3]:
import glob 
import pandas as pd

# 1. Grab the paths to all 8 CSV files in the npx folder
npx_files = glob.glob('raw_data/npx/*.csv')

# 2. Create an empty list to hold the data
npx_data_list = []

# 3. Loop through each file, read it, and add it to the list
for file in npx_files:
    df = pd.read_csv(file)
    npx_data_list.append(df)

# 4. Combine all datasets into one massive master dataframe
if len(npx_files) > 0:
    npx_master_df = pd.concat(npx_data_list, ignore_index=True)
    print(f"Successfully combined {len(npx_files)} files!")
else:
    print("Uh oh! No files were found. Let's double-check the folder path.")

Successfully combined 8 files!

In [4]:
# --- STEP 1: COMBINE THE 4 DELTA NPX FILES ---

# Grab the paths to all CSV files in the delta_npx folder
delta_npx_files = glob.glob('raw_data/delta_npx/*.csv')

# Create an empty list and loop through the files to read them
delta_npx_data_list = []
for file in delta_npx_files:
    df = pd.read_csv(file)
    delta_npx_data_list.append(df)

# Combine them into one dataframe
if len(delta_npx_files) > 0:
    delta_npx_master_df = pd.concat(delta_npx_data_list, ignore_index=True)
    print(f"Successfully combined {len(delta_npx_files)} files in delta_npx!")
    display(delta_npx_master_df.head())
else:
    print("Uh oh! No files were found in delta_npx.")

Successfully combined 4 files in delta_npx!

,OlinkID,Assay,001B,007,008,009,011,014,015,016,018,019,Panel
0,OID20159,ACAN,-0.2313,-0.3898,-0.0359,-0.2010,-0.0221,-0.4863,-0.0924,-0.0620,0.1893,-0.5197,Cardiometabolic
1,OID20105,ACE2,0.3885,-0.0481,-0.0200,-0.1803,0.3953,0.1248,0.0540,-0.1140,NaN,-0.0316,Cardiometabolic
2,OID20124,ACOX1,0.2359,-0.5364,-0.2142,-0.0389,-0.3615,-0.3739,0.2709,0.9951,0.3592,0.5106,Cardiometabolic
3,OID20314,ACP5,-0.1511,-0.2417,-0.0487,-0.1616,-0.2503,0.1350,0.0519,-0.2053,-0.0138,0.0849,Cardiometabolic
4,OID20079,ACTA2,0.8962,-0.0234,0.8698,0.0251,0.0916,0.4535,-0.1594,0.2244,NaN,-0.0491,Cardiometabolic

In [5]:
# --- STEP 3: COMBINE THE 8 FOLD CHANGES FILES ---

# Grab the paths to all CSV files in the fold_changes folder
fold_changes_files = glob.glob('raw_data/fold_changes/*.csv')

# Create an empty list and loop through the files to read them
fold_changes_data_list = []
for file in fold_changes_files:
    df = pd.read_csv(file)
    fold_changes_data_list.append(df)

# Combine them into one dataframe
if len(fold_changes_files) > 0:
    fold_changes_master_df = pd.concat(fold_changes_data_list, ignore_index=True)
    print(f"Successfully combined {len(fold_changes_files)} files in fold_changes!")
    print(f"Total rows and columns: {fold_changes_master_df.shape}")
    display(fold_changes_master_df.head())
else:
    print("Uh oh! No files were found in fold_changes.")

Successfully combined 8 files in fold_changes!
Total rows and columns: (2943, 5)

      Assay   PT2-PT1   PR2-PR1   PT2-PR2   PT1-PR1
0     AAMDC -0.044301 -0.136572  0.153918  0.061647
1     ABCA2  0.355252 -0.230848  0.492375 -0.093725
2  ABRAXAS2  0.226120  0.393643  0.028880  0.196403
3    ACADSB  0.225471  0.179762  0.609668  0.563959
4     ACSL1 -0.160731  0.221122 -0.175161  0.206692

In [6]:
# --- STEP 3: COMBINE THE 8 FOLD CHANGES FILES ---

import glob
import pandas as pd

# Grab the paths to all CSV files in the fold_changes folder
fold_changes_files = glob.glob('raw_data/fold_changes/*.csv')

# Create an empty list and loop through the files to read them
fold_changes_data_list = []
for file in fold_changes_files:
    df = pd.read_csv(file)
    fold_changes_data_list.append(df)

# Combine them into one dataframe
if len(fold_changes_files) > 0:
    fold_changes_master_df = pd.concat(fold_changes_data_list, ignore_index=True)
    print(f"Successfully combined {len(fold_changes_files)} files in fold_changes!")
    print(f"Total rows and columns: {fold_changes_master_df.shape}")
    display(fold_changes_master_df.head())
else:
    print("Uh oh! No files were found in fold_changes.")

Successfully combined 8 files in fold_changes!
Total rows and columns: (2943, 5)

      Assay   PT2-PT1   PR2-PR1   PT2-PR2   PT1-PR1
0     AAMDC -0.044301 -0.136572  0.153918  0.061647
1     ABCA2  0.355252 -0.230848  0.492375 -0.093725
2  ABRAXAS2  0.226120  0.393643  0.028880  0.196403
3    ACADSB  0.225471  0.179762  0.609668  0.563959
4     ACSL1 -0.160731  0.221122 -0.175161  0.206692

In [7]:
import pandas as pd

# 1. Load the Physiological data
physio_df = pd.read_excel('raw_data/physiological/data.xlsx')
print(f"✅ Physiological data loaded! Total rows and columns: {physio_df.shape}")
display(physio_df.head())

# 2. Load the Infant Wearable data
wearable_df = pd.read_excel('raw_data/infant_wearable/InfantSmartWear_TemperatureMonitoring_v1.xlsx')
print(f"✅ Wearable data loaded! Total rows and columns: {wearable_df.shape}")
display(wearable_df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'raw_data/physiological/data.xlsx'

In [ ]:
import os
print(os.listdir('raw_data/'))

In [ ]:
import pandas as pd

# 1. Load the Physiological data
physio_df = pd.read_excel('raw_data/physiological/data.xlsx')
print(f" Physiological data loaded! Total rows and columns: {physio_df.shape}")
display(physio_df.head())

# 2. Load the Infant Wearable data
wearable_df = pd.read_excel('raw_data/infant_wearable/InfantSmartWear_TemperatureMonitoring_v1.xlsx')
print(f" Wearable data loaded! Total rows and columns: {wearable_df.shape}")
display(wearable_df.head())

In [ ]:
import os

print("Exact file in physiological:")
print(os.listdir('raw_data/physiological/'))

print("Exact file in wearable:")
print(os.listdir('raw_data/infant_wearable/'))

In [ ]:
import pandas as pd

# 1. Load the Physiological data
physio_df = pd.read_csv('raw_data/physiological/data.xlsx.csv')
print(f"Physiological data loaded! Total rows and columns: {physio_df.shape}")
display(physio_df.head())

# 2. Load the Infant Wearable data
wearable_df = pd.read_csv('raw_data/infant_wearable/InfantSmartWear_TemperatureMonitoring_v1.csv')
print(f"Wearable data loaded! Total rows and columns: {wearable_df.shape}")
display(wearable_df.head())

In [ ]:
# --- PHASE 2: HUNTING FOR MISSING VALUES ---

print("Total missing (NaN) values in each dataset:")
print(f"1. NPX Data: {npx_master_df.isna().sum().sum()}")
print(f"2. Delta NPX: {delta_npx_master_df.isna().sum().sum()}")
print(f"3. Fold Changes: {fold_changes_master_df.isna().sum().sum()}")
print(f"4. Physiological: {physio_df.isna().sum().sum()}")
print(f"5. Wearable: {wearable_df.isna().sum().sum()}")

In [ ]:
# Calculate the percentage of missing values for each column in the NPX data
missing_percent = (npx_master_df.isna().sum() / len(npx_master_df)) * 100

# Show the top 15 columns with the highest percentage of missing data
print("Top 15 columns with the most missing data (%):")
display(missing_percent.sort_values(ascending=False).head(15))

In [ ]:
# Check total missing values specifically in the physiological data

total_physio_missing = physio_df.isna().sum().sum()
print(f"Total missing values in Physiological Data: {total_physio_missing}")

In [ ]:
# --- PHASE 2.1: REMOVING HEAVILY MISSING COLUMNS ---

# We want to keep columns that have AT LEAST 80% real data (max 20% missing)
# Calculate what 80% of our total rows equals
minimum_valid_data = int(0.8 * len(npx_master_df))

# Drop the junk columns and save it as a new "clean" dataframe
npx_clean_df = npx_master_df.dropna(axis=1, thresh=minimum_valid_data)

print(f"Original number of protein columns: {npx_master_df.shape[1]}")
print(f"New number of protein columns: {npx_clean_df.shape[1]}")
print(f" We successfully dropped {npx_master_df.shape[1] - npx_clean_df.shape[1]} useless columns!")

In [ ]:
# --- PHASE 2.2: THE PROPER PROTEOMICS CLEANING METHOD ---

# Step 1: Only drop proteins that are "dead" (missing more than 90% of their data)
# We keep columns that have at least 10% real data
min_valid = int(0.1 * len(npx_master_df))
npx_saved_df = npx_master_df.dropna(axis=1, thresh=min_valid)

print(f"1. Dropped 'dead' proteins. Columns safely remaining: {npx_saved_df.shape[1]}")

# Step 2: For the surviving proteins, treat NaN as "Below Limit of Detection"
# We fill the blanks with the minimum recorded value for each specific protein
npx_imputed_df = npx_saved_df.fillna(npx_saved_df.min(numeric_only=True))

print("2. Missing values successfully filled with minimum baselines!")
print(f"Total missing values left in NPX data: {npx_imputed_df.isna().sum().sum()}")

In [ ]:
# --- PHASE 2.3: WIPING OUT THE LAST 24 ---

# Drop the few remaining rows that have missing text labels
npx_final_df = npx_imputed_df.dropna()

print(f" Final check! Total missing values in NPX: {npx_final_df.isna().sum().sum()}")
print(f"Final shape of our flawlessly clean NPX data: {npx_final_df.shape}")

In [ ]:
# --- PHASE 2.3: WIPING OUT THE LAST 24 ---

# Drop the few remaining rows that have missing text labels
npx_final_df = npx_imputed_df.dropna()

print(f" Final check! Total missing values in NPX: {npx_final_df.isna().sum().sum()}")
print(f"Final shape of our flawlessly clean NPX data: {npx_final_df.shape}")

In [ ]:
# --- PHASE 2.3: WIPING OUT THE LAST 24 ---

# Drop the few remaining rows that have missing text labels
npx_final_df = npx_imputed_df.dropna()

print(f" Final check! Total missing values in NPX: {npx_final_df.isna().sum().sum()}")
print(f"Final shape of our flawlessly clean NPX data: {npx_final_df.shape}")

In [ ]:
import pandas as pd
import glob

print("Re-loading all files from scratch so Jupyter doesn't forget...")

# --- 1. LOAD ALL DATA ---
npx_master_df = pd.concat([pd.read_csv(f) for f in glob.glob('raw_data/npx/*.csv')], ignore_index=True)
delta_npx_master_df = pd.concat([pd.read_csv(f) for f in glob.glob('raw_data/delta_npx/*.csv')], ignore_index=True)
fold_changes_master_df = pd.concat([pd.read_csv(f) for f in glob.glob('raw_data/fold_changes/*.csv')], ignore_index=True)

# Here are the exact variable names we are locking in:
physio_df = pd.read_csv('raw_data/physiological/data.xlsx.csv')
wearable_df = pd.read_csv('raw_data/infant_wearable/InfantSmartWear_TemperatureMonitoring_v1.csv')

# --- 2. CLEAN ALL DATA ---
npx_saved_df = npx_master_df.dropna(axis=1, thresh=int(0.1 * len(npx_master_df)))
npx_final_df = npx_saved_df.fillna(npx_saved_df.min(numeric_only=True)).dropna()

delta_npx_saved = delta_npx_master_df.dropna(axis=1, thresh=int(0.1 * len(delta_npx_master_df)))
delta_npx_final = delta_npx_saved.fillna(delta_npx_saved.min(numeric_only=True)).dropna()

fold_changes_final = fold_changes_master_df.dropna()

# --- 3. FINAL CHECK ---
print("FINAL CLEANUP RESULTS:")
print(f"1. NPX Final Missing: {npx_final_df.isna().sum().sum()}")
print(f"2. Delta NPX Final Missing: {delta_npx_final.isna().sum().sum()}")
print(f"3. Fold Changes Final Missing: {fold_changes_final.isna().sum().sum()}")
print(f"4. Physiological Final Missing: {physio_df.isna().sum().sum()}")
print(f"5. Wearable Final Missing: {wearable_df.isna().sum().sum()}")

In [ ]:
# Prove the data is safe and loaded in memory!
print(f"Total rows and columns ready for Machine Learning: {npx_final_df.shape}")
display(npx_final_df.head())

In [ ]:
# --- PHASE 3: FINDING THE MATCHING KEYS ---

print("First 5 columns in NPX:")
print(npx_final_df.columns[:5].tolist())

print("\nFirst 5 columns in Physiological:")
print(physio_df.columns[:5].tolist())

print("\nFirst 5 columns in Wearable:")
print(wearable_df.columns[:5].tolist())

In [ ]:
npx_final_df.to_csv('CLEAN_npx_data.csv', index=False)
print("Clean NPX data successfully saved to your folder!")

In [ ]:
# --- CHECKING THE MATH: MIN & MAX VALUES ---

# Create a clean summary table showing the Min and Max for each protein
min_max_summary = pd.DataFrame({
    'Minimum Value (Used to fill blanks)': npx_saved_df.min(numeric_only=True),
    'Maximum Value (Highest recorded)': npx_saved_df.max(numeric_only=True)
})

print("Here are the exact baseline numbers Python calculated:")
display(min_max_summary.head(15))

In [ ]:
# --- SAVE ALL REMAINING CLEAN DATASETS ---

# Save Delta NPX
delta_npx_final.to_csv('CLEAN_delta_npx_data.csv', index=False)

# Save Fold Changes
fold_changes_final.to_csv('CLEAN_fold_changes_data.csv', index=False)

# Save Physiological
physio_df.to_csv('CLEAN_physiological_data.csv', index=False)

# Save Wearable
wearable_df.to_csv('CLEAN_wearable_data.csv', index=False)

print("All clean datasets are now locked in and saved to your hard drive!")

In [ ]:
import pandas as pd

# Load ONLY the clean physiological data we saved earlier
ml_df = pd.read_csv('CLEAN_physiological_data.csv')

print("Clean Physiological Data loaded for ML!")
print(f"Total Rows & Columns: {ml_df.shape}")
display(ml_df.head())

In [ ]:
import pandas as pd

print("Booting up the Machine Learning Environment...")

# 1. Load the perfectly clean physiological data
ml_df = pd.read_csv('CLEAN_physiological_data.csv')

# 2. Strip any hidden spaces from column names just to be safe
ml_df.columns = ml_df.columns.str.strip()

print("Data successfully loaded!")
print(f"Total Rows & Columns ready for ML: {ml_df.shape}")
display(ml_df.head())

In [ ]:
# --- PHASE 4: DISCOVERING THE HARMFUL THRESHOLD (UPDATED) ---

# 1. Strip hidden spaces just to be safe
ml_df.columns = ml_df.columns.str.strip()
ml_df['Sub-category'] = ml_df['Sub-category'].str.strip()

# Let's verify exactly how the categories are spelled in the file
print("Unique categories found in your data:")
print(ml_df['Sub-category'].unique())
print("-" * 50)

# 2. Compare the temperatures between the groups to find the exact danger threshold
threshold_check = ml_df.groupby('Sub-category')['Tcore'].agg(['min', 'mean', 'max'])

print("CLINICAL THRESHOLD DISCOVERY:")
display(threshold_check)

In [ ]:
# --- PHASE 7: CLINICAL STATISTICS SUMMARY FOR SUPERVISOR ---

# 1. Grab only the number columns (you can't find the average of a name)
numeric_df = ml_df.select_dtypes(include='number')

# 2. Calculate the core stats
mean_vals = numeric_df.mean()
median_vals = numeric_df.median()
mode_vals = numeric_df.mode().iloc[0] # Takes the most common number

# 3. Combine them into one beautiful, readable summary table
summary_stats = pd.DataFrame({
    'Mean (Average)': mean_vals,
    'Median': median_vals,
    'Mode': mode_vals
})

print("CLINICAL DATASET SUMMARY:")
display(summary_stats)

# Optional: Save it instantly as an Excel file so you can email it to her!
summary_stats.to_excel("Clinical_Stats_Summary.xlsx")
print("Saved as 'Clinical_Stats_Summary.xlsx' in your folder!")

In [8]:
from sklearn.ensemble import RandomForestClassifier
import pickle

# --- PHASE 6: TRAINING THE ML BRAIN & SAVING IT FOR FLASK ---

print("Initializing Random Forest Algorithm...")
# n_estimators=100 means it's building 100 decision trees to vote on the outcome
model = RandomForestClassifier(n_estimators=100, random_state=42)

# 1. Train the Brain! 
# We feed it the training rows of biological clues (X_train) and the answers (y_train)
model.fit(X_train, y_train)
print("The model has officially learned the biology of heat stress!")

# 2. Test the Model on the hidden patients
accuracy = model.score(X_test, y_test)
print(f"Final Exam Score on Unseen Patients: {accuracy * 100}% Accuracy")

# 3. Save the Brain as a .pkl file so Flask can use it later
with open('heat_stress_model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("heat_stress_model.pkl' successfully saved to your folder!")
print("WE ARE OFFICIALLY DONE WITH JUPYTER NOTEBOOK!")

Initializing Random Forest Algorithm...

NameError: name 'X_train' is not defined

In [12]:
from sklearn.model_selection import GroupShuffleSplit
from sklearn.ensemble import RandomForestClassifier
import pickle
import numpy as np

# =====================================================================
# STEP 0: GRAB THE DATA YOU ALREADY LOADED!
# Using the exact variable dictionary from your screenshot
# =====================================================================
ml_df = clean_datasets['CLEAN_physiological_data'].copy()
ml_df.columns = ml_df.columns.str.strip()

# =====================================================================
# STEP 1: PREPARE THE DATA 
# =====================================================================
# Create the Answer Key (1 = hyperthermic/Danger, 0 = Safe)
ml_df['Heat_Stress_Risk'] = (ml_df['Sub-category'].str.strip() == 'hyperthermic').astype(int)
y = ml_df['Heat_Stress_Risk']

# Drop all the text columns so the algorithm only sees pure math
cols_to_drop = ['Participant', 'category', 'Sub-category', 'Heat_Stress_Risk', 'Health_Status']
X = ml_df.drop(columns=[c for c in cols_to_drop if c in ml_df.columns])


# =====================================================================
# STEP 2: THE SPLIT (Hide 2 patients so we can test the model later)
# =====================================================================
groups = ml_df['Participant']
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]


# =====================================================================
# STEP 3: TRAIN THE AI BRAIN & SAVE IT
# =====================================================================
print("Training the Random Forest model...")
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Take the final exam
accuracy = model.score(X_test, y_test)
print(f"Model Accuracy: {accuracy * 100}%")

# Save the brain into a tiny file for Flask
with open('heat_stress_model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("heat_stress_model.pkl' is now saved in your folder!")

NameError: name 'clean_datasets' is not defined

In [13]:
import pandas as pd
from sklearn.model_selection import GroupShuffleSplit
from sklearn.ensemble import RandomForestClassifier
import pickle
import numpy as np

# =====================================================================
# STEP 0: LOAD YOUR EXACT FILE DIRECTLY
# Note: If your file is an Excel file, change '.csv' to '.xlsx' and pd.read_csv to pd.read_excel
# =====================================================================
file_name = 'CLEAN_physiological_data.csv'
ml_df = pd.read_csv(file_name) 

# Clean up any hidden spaces in the column names
ml_df.columns = ml_df.columns.str.strip()


# =====================================================================
# STEP 1: PREPARE THE DATA 
# =====================================================================
# Create the Answer Key (1 = hyperthermic/Danger, 0 = Safe)
ml_df['Heat_Stress_Risk'] = (ml_df['Sub-category'].str.strip() == 'hyperthermic').astype(int)
y = ml_df['Heat_Stress_Risk']

# Drop all the text columns so the algorithm only sees pure math
cols_to_drop = ['Participant', 'category', 'Sub-category', 'Heat_Stress_Risk', 'Health_Status']
X = ml_df.drop(columns=[c for c in cols_to_drop if c in ml_df.columns])


# =====================================================================
# STEP 2: THE SPLIT (Hide 2 patients so we can test the model later)
# =====================================================================
groups = ml_df['Participant']
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]


# =====================================================================
# STEP 3: TRAIN THE AI BRAIN & SAVE IT
# =====================================================================
print("Training the Random Forest model...")
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Take the final exam
accuracy = model.score(X_test, y_test)
print(f"Model Accuracy: {accuracy * 100}%")

# Save the brain into a tiny file for Flask
with open('heat_stress_model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("heat_stress_model.pkl' is now saved in your folder!")

Training the Random Forest model...
Model Accuracy: 100.0%
heat_stress_model.pkl' is now saved in your folder!